services:
  hochwasser-alert:
    build: .
    container_name: hochwasser-alert
    restart: unless-stopped
    environment:
      PROVIDER: pegelonline
      STATION_UUID: "a6ee8177-107b-47dd-bcfd-30960ccc6e9c"
      LIMIT_CM: "600"
      FORECAST_SERIES_SHORTNAME: "WV"
      RUN_EVERY_MINUTE: "true"
      ALERT_RECIPIENTS: "peter.ketges@gmx.de,gemsa.michael@gmail.com"

      FORECAST_RUN_HOURS: "0,12"
      FORECAST_HORIZON_HOURS: "96"
      ALERT_DEDUPE_HOURS: "24"
      LOG_LEVEL: DEBUG
      TZ: Europe/Berlin

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USE_STARTTLS: "${SMTP_USE_STARTTLS}"
      SMTP_USE_SSL: "${SMTP_USE_SSL}"

      STATE_FILE: /data/state.json
    volumes:
      - ./data:/data
